### ISSUE TITLE
This project wasn't deployed to the maven central

### ISSUE THREAD

**Issue by SurfV** [tbugrara/jackson-patch#1]
I can't find jackson-patch artefact on maven central repo.
Could you, please, deploy a fresh release to the maven central?

Best regards,
  Vasyl

**Comment by tariqkb** [comment]
Doh! Thanks for letting me know! I'll let you know when its up

**Comment by tariqkb** [comment]
Okay good to go. Keep in mind it won't show up when searching yet as that can take up to 2 hours, but including it into your build should download properly.

**Comment by SurfV** [comment]
thanks a lot!!!
